[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/oauth2/callback"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/auth-:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200